[package]
name = "ttt_cli"
version = "0.1.0"
authors = ["ResetPower <resetpower20@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
